In [2]:
import tensorflow as tf

In [17]:
x_data  = [[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5]]
y_data  = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0]]

X = tf.placeholder("float", [None,4])
Y = tf.placeholder("float", [None,3])
nb_classes =3

W = tf.Variable(tf.random_normal([4,nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name ='bais')

hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)

In [23]:
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis),axis=1))
optimizer =tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={X:x_data ,Y: y_data})
        if step % 200 ==0 :
            print(step ,sess.run(cost ,feed_dict={X:x_data, Y:y_data}))
            
    
    a = sess.run(hypothesis, feed_dict ={X: [[1,11,7,9],[1,3,4,3],[1,1,0,1]]})
    print(a,sess.run(tf.arg_max(a,1)))

0 0.660427
200 0.185305
400 0.124466
600 0.0938635
800 0.0751138
1000 0.0624486
1200 0.0533412
1400 0.046492
1600 0.0411635
1800 0.0369055
2000 0.0334287
Instructions for updating:
Use `argmax` instead
[[  6.53668945e-20   9.99999642e-01   3.64309699e-07]
 [  1.29007063e-07   9.70232844e-01   2.97670309e-02]
 [  1.20051824e-04   4.07846392e-06   9.99875903e-01]] [1 1 2]


RuntimeError: Attempted to use a closed Session.