In [1]:
from PIL import Image
import numpy as np

In [6]:
def average_hash(fname ,size =16):
    img = Image.open(fname)
    img = img.convert('L')
    img = img.resize((size,size),Image.ANTIALIAS)
    pixel_data = img.getdata()
    pixels = np.array(pixel_data)
    pixels = pixels.reshape((size,size))
    avg = pixels.mean()
    diff = 1 * (pixels >avg)
    return diff

def np2hash(n):
    bhash = []
    for n1 in ahash.tolist():
        s1 = [str(i) for i in n1]
        s2 = "".join(s1)
        i = int(s2,2)
        bhash.append("%04x"%i)
    return "".join(bhash)

In [7]:
ahash = average_hash('image/tower.jpg')
print(ahash)
print(np2hash(ahash))

[[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0]
 [0 1 1 1 1 1 0 0 0 1 1 1 0 0 0 0]
 [0 0 1 1 1 1 0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0]
 [0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0]
 [1 1 1 1 1 0 0 0 0 0 0 1 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]
7ffe7ffcfffcfffcfffc3ff87c703c701c207c20f810f000e800800100000001
